In [1]:
import pandas as pd,numpy as np
import matplotlib.pyplot as plt, seaborn as sns
import kagglehub
from sklearn.model_selection import train_test_split

In [2]:
file_path = "./house_prices.csv"

data = kagglehub.dataset_load(
  kagglehub.KaggleDatasetAdapter.PANDAS,
  "alyelbadry/house-pricing-dataset",
  file_path
)
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,N,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,N,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,N,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,N,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,N,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
data.shape

(21613, 21)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(data.drop('price',axis=1), data.price, test_size=0.33, random_state=42)

In [5]:
X_train['price'] = y_train
X_test['price'] = y_test

In [6]:
X_train

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
16197,2653000005,20140512T000000,4,2.75,2600,2750,1.5,N,0,Average,...,1620,980,1936,0,98119,47.6413,-122.357,1960,3705,840000.0
16993,1657310170,20140723T000000,3,2.50,2140,9492,2.0,N,0,Average,...,2140,0,1994,0,98092,47.3289,-122.204,2180,9184,302000.0
17538,2425700022,20140929T000000,4,1.75,1730,11890,1.0,N,0,Fair,...,980,750,1955,0,98004,47.5979,-122.194,2100,12325,425000.0
5761,6181400470,20150127T000000,4,2.50,2130,4496,2.0,N,0,Average,...,2130,0,2004,0,98001,47.3041,-122.280,3220,5400,215000.0
18921,2206500300,20140820T000000,5,1.75,1910,9720,1.0,N,0,Good,...,1390,520,1955,0,98006,47.5772,-122.159,1750,9720,565000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11964,5272200045,20141113T000000,3,1.50,1000,6914,1.0,N,0,Average,...,1000,0,1947,0,98125,47.7144,-122.319,1000,6947,378000.0
21575,9578500790,20141111T000000,3,2.50,3087,5002,2.0,N,0,Average,...,3087,0,2014,0,98023,47.2974,-122.349,2927,5183,399950.0
5390,7202350480,20140930T000000,3,2.50,2120,4780,2.0,N,0,Average,...,2120,0,2004,0,98053,47.6810,-122.032,1690,2650,575000.0
860,1723049033,20140620T000000,1,0.75,380,15000,1.0,N,0,Average,...,380,0,1963,0,98168,47.4810,-122.323,1170,15000,245000.0
15795,6147650280,20150325T000000,4,2.50,3130,5999,2.0,N,0,Average,...,3130,0,2006,0,98042,47.3837,-122.099,3020,5997,315000.0

In [7]:
X_test

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
735,2591820310,20141006T000000,4,2.25,2070,8893,2.0,N,0,Good,...,2070,0,1986,0,98058,47.4388,-122.162,2390,7700,365000.0
2830,7974200820,20140821T000000,5,3.00,2900,6730,1.0,N,0,Very Good,...,1830,1070,1977,0,98115,47.6784,-122.285,2370,6283,865000.0
4106,7701450110,20140815T000000,4,2.50,3770,10893,2.0,N,2,Average,...,3770,0,1997,0,98006,47.5646,-122.129,3710,9685,1038000.0
16218,9522300010,20150331T000000,3,3.50,4560,14608,2.0,N,2,Average,...,4560,0,1990,0,98034,47.6995,-122.228,4050,14226,1490000.0
19964,9510861140,20140714T000000,3,2.50,2550,5376,2.0,N,0,Average,...,2550,0,2004,0,98052,47.6647,-122.083,2250,4050,711000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15257,100500020,20140911T000000,3,2.50,1610,6600,2.0,N,0,Average,...,1610,0,1994,0,98003,47.2827,-122.302,1660,7689,250000.0
13822,1523089266,20140722T000000,3,2.50,2320,15024,2.0,N,0,Average,...,2320,0,1990,0,98045,47.4829,-121.766,2300,15145,447500.0
18411,3693901105,20141020T000000,4,2.00,1610,5000,2.0,N,0,Very Good,...,1610,0,1946,0,98117,47.6775,-122.398,1300,4950,630000.0
20188,4083306552,20150310T000000,3,3.25,1460,1367,3.0,N,0,Average,...,1460,0,2008,0,98103,47.6485,-122.334,1310,1191,602000.0
13030,2787700180,20150112T000000,3,2.00,1250,8636,1.0,N,0,Very Good,...,1250,0,1968,0,98059,47.5066,-122.159,1620,7653,320000.0

In [8]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14480 entries, 16197 to 15795
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             14480 non-null  int64
 1   date           14480 non-null  object
 2   bedrooms       14480 non-null  int64
 3   bathrooms      14480 non-null  float64
 4   sqft_living    14480 non-null  int64
 5   sqft_lot       14480 non-null  int64
 6   floors         14480 non-null  float64
 7   waterfront     14480 non-null  object
 8   view           14480 non-null  int64
 9   condition      14480 non-null  object
 10  grade          14480 non-null  int64
 11  sqft_above     14480 non-null  int64
 12  sqft_basement  14480 non-null  int64
 13  yr_built       14480 non-null  int64
 14  yr_renovated   14480 non-null  int64
 15  zipcode        14480 non-null  int64
 16  lat            14480 non-null  float64
 17  long           14480 non-null  float64
 18  sqft_living15  14480 non-null  int64
 19  sqft_lot15     14480 non-null  int64
 20  price          14480 non-null  float64
dtypes: float64(5), int64(13), object(3)
memory usage: 2.4+ MB

In [9]:
X_train.to_csv("../Data/train.csv", index=False)
X_test.to_csv("../Data/test.csv",index=False)